<?php

namespace Social_Image_Generator;

class Meta_Tags {
	/**
	 * Register hooks.
	 */
	public function __construct() {
		add_action( 'wp_head', [ $this, 'render_tags' ] );
	}

	/**
	 * Render meta tags in head.
	 */
	public function render_tags() {
		if ( ! is_singular() || ! apply_filters( 'sig_render_meta_tags', true ) || ! Helpers::is_sig_active() ) {
			return;
		}

		$tags = [];

		if ( apply_filters( 'sig_render_og_image_tags', true ) ) {
			$tags = array_merge($tags, [
				'og:image'        => Helpers::get_image_url(),
				'og:image:width'  => 1200,
				'og:image:height' => 630,
			]);
		}

		if ( apply_filters( 'sig_render_twitter_tags', true ) ) {
			$tags = array_merge($tags, [
				'twitter:image' => Helpers::get_image_url(),
				'twitter:card'  => 'summary_large_image',
			]);
		}

		if ( empty( $tags ) ) {
			return;
		}

		echo '<!-- Generated by Social Image Generator - https://socialimagegenerator.com -->' . PHP_EOL;

		foreach ( $tags as $property => $content ) {
			$filter  = 'sig_meta_' . str_replace( ':', '_', $property );
			$content = apply_filters( $filter, $content );
			$label   = strpos( $property, 'twitter' ) === false ? 'property' : 'name';

			if ( $content ) {
				printf( '<meta %1$s="%2$s" content="%3$s">' . PHP_EOL, esc_attr( $label ), esc_attr( $property ), esc_attr( $content ) );
			}
		}

		echo '<!-- / Social Image Generator -->' . PHP_EOL;
	}
}
